services:
  - type: web
    name: ocr-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
