services:
  - type: web
    name: ocr-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app -w 2 -b 0.0.0.0:10000
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
